# Generated by Django 4.2.28 on 2026-02-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitaina', '0002_post_notification_report_reaction_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='character_name',
            field=models.CharField(blank=True, default='', max_length=141),
        ),
    ]
