# Generated by Django 4.2.28 on 2026-02-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitaina', '0003_post_character_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='collect_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', '👍みたい'), ('hatena', '❓いやちゃうやろw'), ('correct', '🚫これは正確な引用です'), ('collect', '📎コレクト')], max_length=20),
        ),
    ]
